---
title: "Free Run analysis"
output: html_document
---

```{r}
library(ggplot2)
library(plyr)
library(tidyr)
library(lubridate)


```


```{r}
#dat<-read.file("../Data/raw/Trikinetics/2017-10-12_2017-10-16_monitor3.txt")
#dat<-read.table("../Data/raw/Trikinetics/2017-10-12_2017-10-18_Monitor3.txt")
dat<-read.table("../Data/raw/Trikinetics/2017-10-12_2017-10-23_Monitor4.txt")

names(dat)<-c(c("index","read_day","read_month","read_year","read_time","monitor_status","extra","unused1","unused2","unused3","unused4","light_status"),paste("t",seq(1,32),sep=""))

dat<-dat[-8:-11]
str(dat)

##play with time data
dat$read_time<-hms(dat$read_time)
dat$hour = hour(dat$read_time) + minute(dat$read_time)/60

#bins=c(paste0(rep(c(paste0(0,0:9),10:23), each=4),":", c("00",15,30,45))[-1],"24:00")

#.1 hour bins
bins=c(paste0(rep(c(paste0(0,0:9),10:23), each=10),":", c("00",6,12,18,24,30,36,42,48,54))[-1],"24:00")

dat$bins=cut(dat$hour,breaks=seq(0,24,.1),labels=bins)
head(dat)


#### 1 hour bins
#bins=c(paste0(rep(c(paste0(0,0:9),10:23), each=1),":", c("00"))[-1],"24:00")

#dat$bins=cut(dat$hour,breaks=seq(0,24,1),labels=bins)
#head(dat)


### changing wide to long format

dat.long<-gather(dat,Free_run_trik_position,counts,t1:t32)

#summarize the counts for each bin  

dat.long2<-ddply(dat.long, .(read_day,Free_run_trik_position,bins), summarise, counts = sum(counts),light_status=mean(light_status),.drop=FALSE)

head(dat.long2)


```


### cohort list
```{r}
n<-read.csv("../Data/2017-10-16_Trikinetics_cohorts_eclosion.csv")
n$Free_run_trik_position<-as.numeric(n$Free_run_trik_position)
dat.long2$Free_run_trik_position<-as.numeric(substr(dat.long2$Free_run_trik_position,2,3))
n<-subset(n,Free_run_trik_monitor==4)



full<-inner_join(dat.long2,n,by=c("Free_run_trik_position"))
head(full)


```



### extracting 1st cohort
```{r}
co1<-subset(full, Free_run_entry_date=="2017-10-12" & Free_run_trik_position<10 & read_day !=18)

#co1<-subset(full, Free_run_entry_date=="10/12/17" & Free_run_trik_position<10 & read_day !=18)
#& read_day!=16 & read_day !=12
ggplot(co1,aes(x=as.numeric(bins),y=counts))+geom_line()+facet_grid(Free_run_trik_position~read_day)#+geom_vline(xintercept=201)
```

#### extracting 2nd cohort
```{r}
#co1.2<-subset(full, Free_run_entry_date=="2017-10-13" & read_day!=18 & read_day !=12)
co1.2<-subset(full, Free_run_entry_date=="10/13/2017" & read_day!=18 & read_day !=12)

ggplot(co1.2,aes(x=as.numeric(bins),y=counts))+geom_line()+facet_grid(Free_run_trik_position~read_day)+geom_vline(xintercept=c(60,200))

#ggplot(co1.2,aes(x=bins,y=counts))+geom_bar(stat="identity")+facet_grid(Free_run_trik_position~read_day)#+geom_vline(xintercept=c(60,200))

```

#### extracting 3rd cohort
```{r}
#co1.3<-subset(full, Free_run_entry_date=="2017-10-14" & read_day!=23 & read_day >14)
co1.3<-subset(full, Free_run_entry_date=="10/14/17" & read_day!=23 & read_day >14)

ggplot(co1.3,aes(x=as.numeric(bins),y=counts))+geom_line()+facet_grid(uniqueID~read_day)+geom_vline(xintercept=c(60,200))

ggplot(co1.3,aes(x=as.numeric(bins),y=counts))+geom_line()+facet_grid(read_day~uniqueID)#+geom_vline(xintercept=c(60,200))
#write.csv(co1.3,"co13.csv")

#ggplot(co1.3,aes(x=as.numeric(bins),y=counts))+geom_bar(stat="identity")+facet_grid(read_day~uniqueID)

###subsetting out 1 
co1.3.1<-subset(co1.3,uniqueID=="2b35")
ggplot(co1.3.1,aes(x=as.numeric(bins),y=counts))+geom_line()+facet_grid(read_day~uniqueID)
co1.3.1$day<-sort(rep(1:length(unique(co1.3.1$read_day)),summary(as.factor(co1.3.1$read_day))[1]))
#co1.3.1$cont_time<-seq(1,length(co1.3.1$read_day),1)
co1.3.1$cont_time<-seq(from=.1,length.out=length(co1.3.1$read_day),by=.1)


###discrete wavelet analysis
library(wavelets)
dwt.1<-dwt(cbind(co1.3.1$counts,co1.3.1$cont_time),n.levels=9,boundary="periodic")
summary(dwt.1)
dwt.2<-align(dwt.1)
plot.dwt(dwt.2)
par(mfrow=c(1,1),mar=c(5,5,5,5))


str(dwt.2)

plot(dwt.2@V[[9]],dwt.2@W[[9]])
plot(dwt.2@V[[8]],dwt.2@W[[8]])
plot(dwt.2@V[[7]],dwt.2@W[[7]])

plot(co1.3.1$cont_time,co1.3.1$counts)
#barplot(co1.3.1$counts,names.arg=co1.3.1$cont_time)

### maximum overlap discrete wavelet transformation  
modwt.1<-modwt(cbind(co1.3.1$counts,co1.3.1$cont_time),boundary="periodic")
summary(modwt.1)
modwt.2<-align(modwt.1)
plot.modwt(modwt.2)
par(mfrow=c(1,1),mar=c(5,5,5,5))
str(modwt.2)


### Tanya Leise suggestion 
Jcirc <- floor(log2(round(24/.1)))
DJt_circ <- wavMRDSum(co1.3.1$count,levels=Jcirc,keep.smooth=FALSE, keep.details=TRUE,reflect=TRUE,wavelet="s12",xform="modwt")
DJt_circ

plot(co1.3.1$count,type="l",col="red")
points(DJt_circ,col="purple")

library(pracma)
IBL<-data.frame(findpeaks(DJt_circ))
names(IBL)<-c("Height","mid_time","initial_time","final_time")
plot(IBL)
diff(IBL$mid_time)

plot(IBL$mid_time[-1],diff(IBL$mid_time),)
lines(loess(diff(IBL$mid_time)~IBL$mid_time[-1],span=1))

plot(IBL[,2:1])
plot(diff(IBL$mid_time),IBL[-1,1])
lines(loess(IBL[-1,1]~diff(IBL$mid_time)))
#modwt plots

##plotting transformation
plot(modwt.2@series[,2],modwt.2@W[[2]][,1],type="l",ylim=c(-20,70))
#lines(co1.3.1$cont_time,co1.3.1$counts,col="red")
lines(modwt.2@series[,2],modwt.2@V[[2]][,1],col="purple")


plot(modwt.2@series[,2],modwt.2@W[[4]][,1],type="l",ylim=c(-20,70))
lines(co1.3.1$cont_time,co1.3.1$counts,col="red")
lines(modwt.2@series[,2],modwt.2@V[[4]][,1],col="purple")

#plot(modwt.2@series[,2],modwt.2@W[[8]][,1],type="l",ylim=c(-20,70))
#lines(co1.3.1$cont_time,co1.3.1$counts,col="red")
#lines(modwt.2@series[,2],modwt.2@V[[8]][,1],col="purple")

###multi resolution analysis 
mra1<-mra(cbind(co1.3.1$counts,co1.3.1$cont_time),boundary="periodic",n.levels=8)
str(mra1)


##continuous wavelet transformation
library(dplR)
cwt.1<-morlet(y1=co1.3.1$counts,x1=co1.3.1$cont_time)
str(cwt.1)
wavelet.plot(cwt.1)

#plot(cwt.1$wave[128,],cwt.1$period)
plot(cwt.1$wave[,29],cwt.1$Power[,29])

plot(cwt.1$x,cwt.1$wave[,29],type="l",col="blue",lwd=2)
lines(cwt.1$x,sqrt(cwt.1$Power[,29]),col="red")

plot(cwt.1$x,cwt.1$wave[,4],type="l",col="blue",lwd=2)
lines(cwt.1$x,sqrt(cwt.1$Power[,4]),col="red")

#cbind(cwt.1$wave[,29],cwt.1$Power[,29])



```


### trying out WaveletComp package

```{r}
library(WaveletComp)
my.w<-analyze.wavelet(co1.3.1,"counts",upperPeriod=240,loess.span=0,make.pval = T, n.sim = 10)#,dj = 1/20)
wt.image(my.w,color.key="quantile",n.levels=250,legend.params=list(lab="wavelet power levels"),plot.ridge=TRUE,lwd=5)
str(my.w)
reconstruct(my.w)
#plot(my.w$Period,my.w$Ampl)
par(mar=c(5,5,5,5),mfrow=c(1,1))
#reconstruct(my.w,sel.period=c(10,120))


##looking at diff periods
##slice at 3
#per3<-data.frame(cbind(co1.3.1$cont_time,my.w$Ampl[13,],my.w$Ridge[13,]))
per3<-data.frame(cbind(co1.3.1$cont_time,my.w$Ampl[7,],my.w$Ridge[7,]))
head(per3)
subset(per3,X3>0.5)

##plot
plot(co1.3.1$cont_time,co1.3.1$counts,type="l",ylim=c(-20,70),main="2.46 period")
#lines(co1.3.1$cont_time,my.w$Wave[13,],col="red")
#lines(co1.3.1$cont_time,my.w$Power[13,])
lines(co1.3.1$cont_time,my.w$Wave[7,],col="red")
lines(co1.3.1$cont_time,my.w$Power[7,])
abline(v=subset(per3,X3>0.5)$X1,col="blue")



##slice at 9
per9<-data.frame(cbind(co1.3.1$cont_time,my.w$Ampl[42,],my.w$Ridge[42,]))
head(per9)
subset(per9,X3>0.5)

##plot
plot(co1.3.1$cont_time,co1.3.1$counts,type="l",ylim=c(-20,70),main="9 hr period")
lines(co1.3.1$cont_time,my.w$Wave[42,],col="red")
lines(co1.3.1$cont_time,my.w$Power[42,])
abline(v=subset(per9,X3>0.5)$X1,col="blue")
abline(v=seq(0,192,24),col="purple",lty="dotdash")

##slice at 24
per24<-data.frame(cbind(co1.3.1$cont_time,my.w$Ampl[73,],my.w$Ridge[73,],my.w$Power[73,]))
head(per24)
subset(per24,X3>0.5)

##plots
plot(co1.3.1$cont_time,co1.3.1$counts,type="l",ylim=c(-20,70),main="24 hr period")
lines(co1.3.1$cont_time,my.w$Wave[73,],col="red")
lines(co1.3.1$cont_time,my.w$Power[73,])
abline(v=subset(per24,X3>0.5)$X1,col="blue")
abline(v=seq(0,192,24),col="purple",lty="dotdash")

#sqrt(subset(per24,X3>0.5)$X4)

### slice at 48
per48<-data.frame(cbind(co1.3.1$cont_time,my.w$Ampl[93,],my.w$Ridge[93,]))
head(per48)
subset(per48,X3>0.5)
```


#### wavethresh

```{r}
library(wavethresh)
t1<-wd(co1.3.1$counts[1:1024],type="wavelet",bc="periodic")
plot(t1)

ac<-accessC.wd(t1,level=9)
ad<-accessD.wd(t1,level=3)

plot(ac,type="l",col="orange")
lines(co1.3.1$counts[1:1024]/2,col="red")
```