---
title: "Grabbing behavioral rhythm data for a subset of individuals"
author: "Andrew D. Nguyen"
date: "11/19/2017"
output: 
  html_document: 
    toc: yes
---

# Goal is to extract behavioral data and link it with master data   

We're taking a subset set of samples out.  

### Load libraries
```{r loading libraries}
library(ggplot2)
library(plyr)

```

### Load in monitor data   

* add header names to the data   
* for every unique ID, extract behavioral counts

```{r load monitor data}
m1<-read.table("../Data/raw/Trikinetics/Monitor1.txt")
m1$monitor<-rep(1,length(m1$V1))
m2<-read.table("../Data/raw/Trikinetics/Monitor2.txt")
m2$monitor<-rep(2,length(m2$V1))
m3<-read.table("../Data/raw/Trikinetics/Monitor3.txt")
m3$monitor<-rep(3,length(m3$V1))
m4<-read.table("../Data/raw/Trikinetics/Monitor4.txt")
m4$monitor<-rep(4,length(m4$V1))
m5<-read.table("../Data/raw/Trikinetics/Monitor5.txt")
m5$monitor<-rep(5,length(m5$V1))
m6<-read.table("../Data/raw/Trikinetics/Monitor6.txt")
m6$monitor<-rep(6,length(m6$V1))

allm<-rbind(m1,m2,m3,m4,m5,m6)

allm$V2<-paste("20",allm$V4,"-",allm$V3,"-",allm$V2,sep="") # reformatting the date
allm<-allm[,-3:-4] # excluding time we dont need
head(allm)

names(allm)<-c("time_step","date","time","trik_status","none1","none2","none3","none4","none5","light_status",paste("t",seq(1,32),sep=""),"monitor")

```


**h4o4**  

```{r h4o4}
#############################################
###entrainment
#############################################

### grabbing the data from allm dataset to get the time step, date, time, trik status, light status, monitor, and monitor position for h4o4

###we need to look up and specify the time step that the animal was in the trikinetics rig
h4o4<-subset(allm,monitor =="1" & time_step <29241 & time_step>20964, select=c("time_step","date","time","trik_status","light_status","monitor","t1")) 
#dim(h4o4)

#specifying the entrainment part of data
h4o4$experiment<-rep("Entrainment",length(h4o4$time_step))

##recoding the trik position (needs to be specific to the animal )
h4o4$trik_position<-rep(1,length(h4o4$time_step))

## renaming trik position to counts
names(h4o4)[7]<-c("counts") 


#############################################
### free run
#############################################
h4o4f<-subset(allm,monitor =="4" & time_step <52917 & time_step>29242, select=c("time_step","date","time","trik_status","light_status","monitor","t19"))
dim(h4o4f)
h4o4f$experiment<-rep("Free-run",length(h4o4f$time_step))
h4o4f$trik_position<-rep(19,length(h4o4f$time_step))
names(h4o4f)[7]<-c("counts")


#### stitching the data together  
h4o4full<-rbind(h4o4,h4o4f)
h4o4full$uniqueID<-rep("h4o4",length(h4o4full$time_step))
head(h4o4full)
```


**h2b25**

```{r h2b25}
###entrainment
h2b25<-subset(allm,monitor =="1" & time_step <30650 & time_step>22063, select=c("time_step","date","time","trik_status","light_status","monitor","t14")) 

h2b25$experiment<-rep("Entrainment",length(h2b25$time_step))

h2b25$trik_position<-rep(14,length(h2b25$time_step))

names(h2b25)[7]<-c("counts") 

###free run
h2b25f<-subset(allm,monitor =="4" & time_step <52917 & time_step>30650, select=c("time_step","date","time","trik_status","light_status","monitor","t23"))
dim(h2b25f)
h2b25f$experiment<-rep("Free-run",length(h2b25f$time_step))
h2b25f$trik_position<-rep(23,length(h2b25f$time_step))
names(h2b25f)[7]<-c("counts")

###stitching
h2b25full<-rbind(h2b25,h2b25f)
h2b25full$uniqueID<-rep("h2b25",length(h2b25full$time_step))
head(h2b25full)
```

**h5o22**
```{r h5o22}
###entrainment
h5o22<-subset(allm,monitor =="2" & time_step <34262 & time_step>26051, select=c("time_step","date","time","trik_status","light_status","monitor","t22")) 

h5o22$experiment<-rep("Entrainment",length(h5o22$time_step))

h5o22$trik_position<-rep(22,length(h5o22$time_step))

names(h5o22)[7]<-c("counts") 

###free run
h5o22f<-subset(allm,monitor =="3" & time_step <52917 & time_step>34264, select=c("time_step","date","time","trik_status","light_status","monitor","t26"))
dim(h5o22f)
h5o22f$experiment<-rep("Free-run",length(h5o22f$time_step))
h5o22f$trik_position<-rep(26,length(h5o22f$time_step))
names(h5o22f)[7]<-c("counts")

###stitching
h5o22full<-rbind(h5o22,h5o22f)
h5o22full$uniqueID<-rep("h5o22",length(h5o22full$time_step))
head(h5o22full)
```

**12b6**
```{r 12b6}
###entrainment
a12b6<-subset(allm,monitor =="1" & time_step <22157 & time_step>15806, select=c("time_step","date","time","trik_status","light_status","monitor","t17")) 

a12b6$experiment<-rep("Entrainment",length(a12b6$time_step))

a12b6$trik_position<-rep(17,length(a12b6$time_step))

names(a12b6)[7]<-c("counts") 

###free run
a12b6f<-subset(allm,monitor =="4" & time_step <52917 & time_step>22157, select=c("time_step","date","time","trik_status","light_status","monitor","t19"))
dim(h2b25f)
a12b6f$experiment<-rep("Free-run",length(a12b6f$time_step))
a12b6f$trik_position<-rep(19,length(a12b6f$time_step))
names(a12b6f)[7]<-c("counts")

###stitching
a12b6full<-rbind(a12b6,a12b6f)
a12b6full$uniqueID<-rep("a12b6",length(a12b6full$time_step))
head(a12b6full)
```

**5w73**
```{r 5w73}
a5w73<-subset(allm,monitor =="2" & time_step <34905 & time_step>27492, select=c("time_step","date","time","trik_status","light_status","monitor","t11")) 

a5w73$experiment<-rep("Entrainment",length(a5w73$time_step))

a5w73$trik_position<-rep(11,length(a5w73$time_step))

names(a5w73)[7]<-c("counts") 

###free run
a5w73f<-subset(allm,monitor =="5" & time_step <52917 & time_step>34905, select=c("time_step","date","time","trik_status","light_status","monitor","t22"))
dim(a5w73f)
a5w73f$experiment<-rep("Free-run",length(a5w73f$time_step))
a5w73f$trik_position<-rep(22,length(a5w73f$time_step))
names(a5w73f)[7]<-c("counts")

###stitching
a5w73full<-rbind(a5w73,a5w73f)
a5w73full$uniqueID<-rep("a5w73",length(a5w73full$time_step))
head(a5w73full)
```

**4w66**
```{r 4w66}
a4w66<-subset(allm,monitor =="2" & time_step <18896 & time_step>893, select=c("time_step","date","time","trik_status","light_status","monitor","t23")) 

a4w66$experiment<-rep("Entrainment",length(a4w66$time_step))

a4w66$trik_position<-rep(23,length(a4w66$time_step))

names(a4w66)[7]<-c("counts") 

###free run
a4w66f<-subset(allm,monitor =="3" & time_step <33980 & time_step>18896, select=c("time_step","date","time","trik_status","light_status","monitor","t4"))
dim(a4w66f)
a4w66f$experiment<-rep("Free-run",length(a4w66f$time_step))
a4w66f$trik_position<-rep(4,length(a4w66f$time_step))
names(a4w66f)[7]<-c("counts")

###stitching
a4w66full<-rbind(a4w66,a4w66f)
a4w66full$uniqueID<-rep("a4w66",length(a4w66full$time_step))
head(a4w66full)
```

**10w12**
```{r 10w12}
a10w12<-subset(allm,monitor =="2" & time_step <18896 & time_step>8120, select=c("time_step","date","time","trik_status","light_status","monitor","t10")) 

a10w12$experiment<-rep("Entrainment",length(a10w12$time_step))

a10w12$trik_position<-rep(10,length(a10w12$time_step))

names(a10w12)[7]<-c("counts") 

###free run
a10w12f<-subset(allm,monitor =="3" & time_step <52917 & time_step>18896, select=c("time_step","date","time","trik_status","light_status","monitor","t27"))
dim(a10w12f)
a10w12f$experiment<-rep("Free-run",length(a10w12f$time_step))
a10w12f$trik_position<-rep(27,length(a10w12f$time_step))
names(a10w12f)[7]<-c("counts")

###stitching
a10w12full<-rbind(a10w12,a10w12f)
a10w12full$uniqueID<-rep("a10w12",length(a10w12full$time_step))
head(a10w12full)
```

**10o49**
```{r 10o49}
a10o49<-subset(allm,monitor =="2" & time_step <18896 & time_step>8119, select=c("time_step","date","time","trik_status","light_status","monitor","t2")) 

a10o49$experiment<-rep("Entrainment",length(a10o49$time_step))

a10o49$trik_position<-rep(2,length(a10o49$time_step))

names(a10o49)[7]<-c("counts") 

###free run
a10o49f<-subset(allm,monitor =="3" & time_step <52917 & time_step>18896, select=c("time_step","date","time","trik_status","light_status","monitor","t28"))
dim(a10o49f)
a10o49f$experiment<-rep("Free-run",length(a10o49f$time_step))
a10o49f$trik_position<-rep(28,length(a10o49f$time_step))
names(a10o49f)[7]<-c("counts")

###stitching
a10o49full<-rbind(a10o49,a10o49f)
a10o49full$uniqueID<-rep("a10o49",length(a10o49full$time_step))
head(a10o49full)
```

**12w40**
```{r 12w40}
a12w40<-subset(allm,monitor =="1" & time_step <19477 & time_step>10937, select=c("time_step","date","time","trik_status","light_status","monitor","t8")) 

a12w40$experiment<-rep("Entrainment",length(a12w40$time_step))

a12w40$trik_position<-rep(8,length(a12w40$time_step))

names(a12w40)[7]<-c("counts") 

###free run
a12w40f<-subset(allm,monitor =="3" & time_step <52917 & time_step>19460, select=c("time_step","date","time","trik_status","light_status","monitor","t30"))
dim(a12w40f)
a12w40f$experiment<-rep("Free-run",length(a12w40f$time_step))
a12w40f$trik_position<-rep(30,length(a12w40f$time_step))
names(a12w40f)[7]<-c("counts")

###stitching
a12w40full<-rbind(a12w40,a12w40f)
a12w40full$uniqueID<-rep("a12w40",length(a12w40full$time_step))
head(a12w40full)
```

**12b43**
```{r 12b43}
a12b43<-subset(allm,monitor =="1" & time_step <19477 & time_step>10937, select=c("time_step","date","time","trik_status","light_status","monitor","t15")) 

a12b43$experiment<-rep("Entrainment",length(a12b43$time_step))

a12b43$trik_position<-rep(15,length(a12b43$time_step))

names(a12b43)[7]<-c("counts") 

###free run
a12b43f<-subset(allm,monitor =="3" & time_step <52917 & time_step>19460, select=c("time_step","date","time","trik_status","light_status","monitor","t29"))
dim(a12b43f)
a12b43f$experiment<-rep("Free-run",length(a12b43f$time_step))
a12b43f$trik_position<-rep(29,length(a12b43f$time_step))
names(a12b43f)[7]<-c("counts")

###stitching
a12b43full<-rbind(a12b43,a12b43f)
a12b43full$uniqueID<-rep("a12b43",length(a12b43full$time_step))
head(a12b43full)
```

**13o28**
```{r 13o28}
a13o28<-subset(allm,monitor =="1" & time_step <19829 & time_step>12424, select=c("time_step","date","time","trik_status","light_status","monitor","t7")) 

a13o28$experiment<-rep("Entrainment",length(a13o28$time_step))

a13o28$trik_position<-rep(7,length(a13o28$time_step))

names(a13o28)[7]<-c("counts") 

###free run
a13o28f<-subset(allm,monitor =="4" & time_step <34629 & time_step>19829, select=c("time_step","date","time","trik_status","light_status","monitor","t6"))
dim(a13o28f)
a13o28f$experiment<-rep("Free-run",length(a13o28f$time_step))
a13o28f$trik_position<-rep(6,length(a13o28f$time_step))
names(a13o28f)[7]<-c("counts")

###stitching
a13o28full<-rbind(a13o28,a13o28f)
a13o28full$uniqueID<-rep("a13o28",length(a13o28full$time_step))
head(a13o28full)
```

**13o11**
```{r 13o11}
a13o11<-subset(allm,monitor =="2" & time_step <26421 & time_step>18899, select=c("time_step","date","time","trik_status","light_status","monitor","t1")) 

a13o11$experiment<-rep("Entrainment",length(a13o11$time_step))

a13o11$trik_position<-rep(1,length(a13o11$time_step))

names(a13o11)[7]<-c("counts") 

###free run
a13o11f<-subset(allm,monitor =="4" & time_step <52917 & time_step>26406, select=c("time_step","date","time","trik_status","light_status","monitor","t24"))
dim(a13o11f)
a13o11f$experiment<-rep("Free-run",length(a13o11f$time_step))
a13o11f$trik_position<-rep(24,length(a13o11f$time_step))
names(a13o11f)[7]<-c("counts")

###stitching
a13o11full<-rbind(a13o11,a13o11f)
a13o11full$uniqueID<-rep("a13o11",length(a13o11full$time_step))
head(a13o11full)
```

**5b25**
```{r 5b25}
a5b25<-subset(allm,monitor =="1" & time_step <34638 & time_step>26812, select=c("time_step","date","time","trik_status","light_status","monitor","t26"))  

a5b25$experiment<-rep("Entrainment",length(a5b25$time_step))

a5b25$trik_position<-rep(26,length(a5b25$time_step))

names(a5b25)[7]<-c("counts") 

###free run
a5b25f<-subset(allm,monitor =="5" & time_step <52917 & time_step>34349, select=c("time_step","date","time","trik_status","light_status","monitor","t32"))
dim(a5b25f)
a5b25f$experiment<-rep("Free-run",length(a5b25f$time_step))
a5b25f$trik_position<-rep(32,length(a5b25f$time_step))
names(a5b25f)[7]<-c("counts")

###stitching
a5b25full<-rbind(a5b25,a5b25f)
a5b25full$uniqueID<-rep("a5b25",length(a5b25full$time_step))
head(a5b25full)
```

**10o73**
```{r 10o73}
a10o73<-subset(allm,monitor =="1" & time_step <37780 & time_step>30039, select=c("time_step","date","time","trik_status","light_status","monitor","t3"))  

a10o73$experiment<-rep("Entrainment",length(a10o73$time_step))

a10o73$trik_position<-rep(3,length(a10o73$time_step))

names(a10o73)[7]<-c("counts") 

###free run
a10o73f<-subset(allm,monitor =="4" & time_step <52917 & time_step>37804, select=c("time_step","date","time","trik_status","light_status","monitor","t1"))
dim(a10o73f)
a10o73f$experiment<-rep("Free-run",length(a10o73f$time_step))
a10o73f$trik_position<-rep(1,length(a10o73f$time_step))
names(a10o73f)[7]<-c("counts")

###stitching
a10o73full<-rbind(a10o73,a10o73f)
a10o73full$uniqueID<-rep("a10o73",length(a10o73full$time_step))
head(a10o73full)
```

**3o51**
```{r 3o51}
a3o51<-subset(allm,monitor =="1" & time_step <34349 & time_step>26812, select=c("time_step","date","time","trik_status","light_status","monitor","t17"))  

a3o51$experiment<-rep("Entrainment",length(a3o51$time_step))

a3o51$trik_position<-rep(17,length(a3o51$time_step))

names(a3o51)[7]<-c("counts") 

###free run
a3o51f<-subset(allm,monitor =="5" & time_step <52917 & time_step>34349, select=c("time_step","date","time","trik_status","light_status","monitor","t3"))
dim(a3o51f)
a3o51f$experiment<-rep("Free-run",length(a3o51f$time_step))
a3o51f$trik_position<-rep(3,length(a3o51f$time_step))
names(a3o51f)[7]<-c("counts")

###stitching
a3o51full<-rbind(a3o51,a3o51f)
a3o51full$uniqueID<-rep("a3o51",length(a3o51full$time_step))
head(a3o51full)
```

**10w15**
```{r 10w15}
a10w15<-subset(allm,monitor =="2" & time_step <41988 & time_step>34287, select=c("time_step","date","time","trik_status","light_status","monitor","t12"))  

a10w15$experiment<-rep("Entrainment",length(a10w15$time_step))

a10w15$trik_position<-rep(12,length(a10w15$time_step))

names(a10w15)[7]<-c("counts") 

###free run
a10w15f<-subset(allm,monitor =="5" & time_step <52917 & time_step>41988, select=c("time_step","date","time","trik_status","light_status","monitor","t10"))
dim(a10w15f)
a10w15f$experiment<-rep("Free-run",length(a10w15f$time_step))
a10w15f$trik_position<-rep(10,length(a10w15f$time_step))
names(a10w15f)[7]<-c("counts")

###stitching
a10w15full<-rbind(a10w15,a10w15f)
a10w15full$uniqueID<-rep("a10w15",length(a10w15full$time_step))
head(a10w15full)
```

**2b23**
```{r 2b23}
a2b23<-subset(allm,monitor =="2" & time_step <34272 & time_step>26049, select=c("time_step","date","time","trik_status","light_status","monitor","t16"))  

a2b23$experiment<-rep("Entrainment",length(a2b23$time_step))

a2b23$trik_position<-rep(16,length(a2b23$time_step))

names(a2b23)[7]<-c("counts") 

###free run
a2b23f<-subset(allm,monitor =="4" & time_step <52917 & time_step>34341, select=c("time_step","date","time","trik_status","light_status","monitor","t8"))
dim(a2b23f)
a2b23f$experiment<-rep("Free-run",length(a2b23f$time_step))
a2b23f$trik_position<-rep(8,length(a2b23f$time_step))
names(a2b23f)[7]<-c("counts")

###stitching
a2b23full<-rbind(a2b23,a2b23f)
a2b23full$uniqueID<-rep("a2b23",length(a2b23full$time_step))
head(a2b23full)
```

**2b26**
```{r 2b26}
a2b26<-subset(allm,monitor =="2" & time_step <34262 & time_step>26049, select=c("time_step","date","time","trik_status","light_status","monitor","t19"))  

a2b26$experiment<-rep("Entrainment",length(a2b26$time_step))

a2b26$trik_position<-rep(19,length(a2b26$time_step))

names(a2b26)[7]<-c("counts") 

###free run
a2b26f<-subset(allm,monitor =="4" & time_step <52917 & time_step>34253, select=c("time_step","date","time","trik_status","light_status","monitor","t5"))
dim(a2b26f)
a2b26f$experiment<-rep("Free-run",length(a2b26f$time_step))
a2b26f$trik_position<-rep(5,length(a2b26f$time_step))
names(a2b26f)[7]<-c("counts")

###stitching
a2b26full<-rbind(a2b26,a2b26f)
a2b26full$uniqueID<-rep("a2b26",length(a2b26full$time_step))
head(a2b26full)
```

**4o15**
```{r 4o15}
a4o15<-subset(allm,monitor =="2" & time_step <34905 & time_step>27493, select=c("time_step","date","time","trik_status","light_status","monitor","t29"))  

a4o15$experiment<-rep("Entrainment",length(a4o15$time_step))

a4o15$trik_position<-rep(29,length(a4o15$time_step))

names(a4o15)[7]<-c("counts") 

###free run
a4o15f<-subset(allm,monitor =="5" & time_step <52917 & time_step>34905, select=c("time_step","date","time","trik_status","light_status","monitor","t30"))
dim(a4o15f)
a4o15f$experiment<-rep("Free-run",length(a4o15f$time_step))
a4o15f$trik_position<-rep(30,length(a4o15f$time_step))
names(a4o15f)[7]<-c("counts")

###stitching
a4o15full<-rbind(a4o15,a4o15f)
a4o15full$uniqueID<-rep("a4o15",length(a4o15full$time_step))
head(a4o15full)
```

**5w63**
```{r 5w63}
a5w63<-subset(allm,monitor =="2" & time_step <34905 & time_step>27492, select=c("time_step","date","time","trik_status","light_status","monitor","t9"))  

a5w63$experiment<-rep("Entrainment",length(a5w63$time_step))

a5w63$trik_position<-rep(9,length(a5w63$time_step))

names(a5w63)[7]<-c("counts") 

###free run
a5w63f<-subset(allm,monitor =="5" & time_step <52917 & time_step>34905, select=c("time_step","date","time","trik_status","light_status","monitor","t16"))
dim(a5w63f)
a5w63f$experiment<-rep("Free-run",length(a5w63f$time_step))
a5w63f$trik_position<-rep(16,length(a5w63f$time_step))
names(a5w63f)[7]<-c("counts")

###stitching
a5w63full<-rbind(a5w63,a5w63f)
a5w63full$uniqueID<-rep("a5w63",length(a5w63full$time_step))
head(a5w63full)
```

**11w26**
```{r 11w26}
a11w26<-subset(allm,monitor =="2" & time_step <41988 & time_step>34264, select=c("time_step","date","time","trik_status","light_status","monitor","t25"))  

a11w26$experiment<-rep("Entrainment",length(a11w26$time_step))

a11w26$trik_position<-rep(25,length(a11w26$time_step))

names(a11w26)[7]<-c("counts") 

###free run
a11w26f<-subset(allm,monitor =="5" & time_step <52917 & time_step>41988, select=c("time_step","date","time","trik_status","light_status","monitor","t27"))
dim(a11w26f)
a11w26f$experiment<-rep("Free-run",length(a11w26f$time_step))
a11w26f$trik_position<-rep(27,length(a11w26f$time_step))
names(a11w26f)[7]<-c("counts")

###stitching
a11w26full<-rbind(a11w26,a11w26f)
a11w26full$uniqueID<-rep("a11w26",length(a11w26full$time_step))
head(a11w26full)
```

**10o62**
```{r 10o62}
a10o62<-subset(allm,monitor =="1" & time_step <41427 & time_step>37123, select=c("time_step","date","time","trik_status","light_status","monitor","t31"))  

a10o62$experiment<-rep("Entrainment",length(a10o62$time_step))

a10o62$trik_position<-rep(31,length(a10o62$time_step))

names(a10o62)[7]<-c("counts") 
```

**4o25**
```{r 4o25}
a4o25<-subset(allm,monitor =="2" & time_step <47187 & time_step>42151, select=c("time_step","date","time","trik_status","light_status","monitor","t3"))  

a4o25$experiment<-rep("Entrainment",length(a4o25$time_step))

a4o25$trik_position<-rep(3,length(a4o25$time_step))

names(a4o25)[7]<-c("counts") 

###free run
a4o25f<-subset(allm,monitor =="6" & time_step <52917 & time_step>47186, select=c("time_step","date","time","trik_status","light_status","monitor","t12"))
dim(a4o25f)
a4o25f$experiment<-rep("Free-run",length(a4o25f$time_step))
a4o25f$trik_position<-rep(12,length(a4o25f$time_step))
names(a4o25f)[7]<-c("counts")

###stitching
a4o25full<-rbind(a4o25,a4o25f)
a4o25full$uniqueID<-rep("a4o25",length(a4o25full$time_step))
head(a5b25full)
```

**h4w10**
```{r h4w10}
h4w10<-subset(allm,monitor =="2" & time_step <45272 & time_step>38649, select=c("time_step","date","time","trik_status","light_status","monitor","t9"))  

h4w10$experiment<-rep("Entrainment",length(h4w10$time_step))

h4w10$trik_position<-rep(9,length(h4w10$time_step))

names(h4w10)[7]<-c("counts") 

###free run
h4w10f<-subset(allm,monitor =="5" & time_step <52917 & time_step>45272, select=c("time_step","date","time","trik_status","light_status","monitor","t21"))
dim(h4w10f)
h4w10f$experiment<-rep("Free-run",length(h4w10f$time_step))
h4w10f$trik_position<-rep(21,length(h4w10f$time_step))
names(h4w10f)[7]<-c("counts")

###stitching
h4w10full<-rbind(h4w10,h4w10f)
h4w10full$uniqueID<-rep("h4w10",length(h4w10full$time_step))
head(h4w10full)
```

###h8w4 and h8o14 both have not exited the trikinetics###
**h8w4**
```{r h8w4}
h8w4<-subset(allm,monitor =="1" & time_step <45272 & time_step>34784, select=c("time_step","date","time","trik_status","light_status","monitor","t12"))  

h4w10$experiment<-rep("Entrainment",length(h4w10$time_step))

h4w10$trik_position<-rep(9,length(h4w10$time_step))

names(h4w10)[7]<-c("counts") 
```

### Session Information

```{r session info}
sessionInfo()
```

