---
title: "Preliminary trikinetics"
output: html_document
---


### Load libraries
```{r library}
library(ggplot2)
library(plyr)
library(tidyr)
library(lubridate)
```

### read in data

```{r}
#prelim<-read.table("../Data/raw/Trikinetics/2017-09-26_27_prelim_data.txt")
#prelim<-read.table("../Data/raw/Trikinetics/2017-09-26_29_prelim_data.txt")
prelim<-read.table("../Data/raw/Trikinetics/2017-09-27_2017-10-01_prelim_data.txt")

head(prelim)
#add header
length(names(prelim))


names(prelim)<-c(c("index","read_day","read_month","read_year","read_time","monitor_status","extra","unused1","unused2","unused3","unused4","light_status"),paste("t",seq(1,32),sep=""))

##dropping unused
prelim.drop<-prelim[-1,-8:-11]
head(prelim.drop)

##play with time data
prelim.drop$read_time<-hms(prelim.drop$read_time)
prelim.drop$hour = hour(prelim.drop$read_time) + minute(prelim.drop$read_time)/60

bins=c(paste0(rep(c(paste0(0,0:9),10:23), each=4),":", c("00",15,30,45))[-1],"24:00")

prelim.drop$bins=cut(prelim.drop$hour,breaks=seq(0,24,.25),labels=bins)
head(prelim.drop)
```



### restructure data from wide to long format    

```{r wide to long format dat}
prelim.long<-gather(prelim.drop,trik_ID,counts,t1:t32)
head(prelim.long)

dim(prelim.long)


#summarize the counts for each bin  

prelim.long<-ddply(prelim.long, .(read_day,trik_ID,bins), summarise, counts = sum(counts),light_status=mean(light_status), .drop=FALSE)
head(prelim.long)

```

### visualize behavioral patterns

```{r visualizing}
prelim.long1<-subset(prelim.long,counts>0.5)

#ggplot(prelim.long1,aes(x=read_time,y=counts,colour=factor(trik_ID)))+geom_point()
#ggplot(prelim.long1,aes(x=bins,y=counts))+geom_point()+facet_grid(trik_ID~read_day)
ggplot(prelim.long,aes(x=bins,y=counts))+geom_point()+facet_grid(trik_ID~read_day)
```


### looking at 1 example : T13   (wasp)

```{r}
#t13<-subset(prelim.long,trik_ID=="t13"& read_day ==28)
t13<-subset(prelim.long,trik_ID=="t13" & read_day >26 & read_day< 31 )
str(t13)

#ggplot(t13,aes(x=bins,y=counts))+geom_point()+facet_grid(.~read_day)+stat_smooth(method="loess")

ggplot(t13,aes(x=as.numeric(bins),y=counts,colour=factor(read_day)))+geom_point()+scale_x_continuous(,breaks=seq(1,96,4),labels=seq(1,24,1))+stat_smooth()
#+geom_line()
ggplot(t13,aes(x=as.numeric(bins),y=counts,colour=factor(read_day)))+geom_point()+scale_x_continuous(,breaks=seq(1,96,4),labels=seq(1,24,1))

##fitting spline
data.frame(spline(x=as.numeric(t13$bins),y=t13$counts,n=length(t13$read_day),method="periodic"))
as.vector(spline(x=as.numeric(t13$bins),y=t13$counts,n=length(t13$read_day))[1])

fulldat<-ddply(t13,.(read_day),transform,time=as.vector(spline(x=as.numeric(bins),y=counts,n=length(read_day))[1]),splinefit=as.vector(spline(x=as.numeric(bins),y=counts,n=length(read_day),method="periodic")[2]))


##plotting splines
ggplot(fulldat,aes(x=as.numeric(bins),y=counts,colour=factor(read_day)))+geom_point()+scale_x_continuous(,breaks=seq(0,96,4),labels=seq(0,24,1))+geom_line(data=fulldat,aes(x=x,y=y))+facet_grid(read_day~.)

## lets measure overall activity  

sum(fulldat$counts)
sum(fulldat$y)
```

### looking at 1 example : T27   (Rhago)

```{r}
t27<-subset(prelim.long,trik_ID=="t18"& read_day ==28)
#t27<-subset(prelim.long,trik_ID=="t27")
str(t27)
#t27$bins<-as.numeric(t27$bins)
#ggplot(t27,aes(x=bins,y=counts))+geom_point()+facet_grid(.~read_day)+stat_smooth(method="loess")
ggplot(t27,aes(x=as.numeric(bins),y=counts,colour=factor(read_day)))+geom_point()+scale_x_continuous(,breaks=seq(1,96,4),labels=seq(1,24,1))+geom_line()

#ggplot(t27,aes(x=bins,y=counts))+geom_point()+facet_grid(.~read_day)+stat_smooth(method="")
```



### tirkinetics cohort list  

```{r}
n<-read.csv("../Data/Trikinetics_cohorts_eclosion.csv")
n$trik_ID<-as.numeric(n$trik_ID)
#prelim.long$trik_ID<-as.numeric(substr(prelim.long$trik_ID,2,3))

full<-inner_join(prelim.long,n,by=c("trik_ID"))
head(full)

```

### plot by cohort   

```{r}
c1<-subset(full,trik_cohort==1 & read_day >26.1 & read_day <31)
ggplot(c1,aes(x=as.numeric(bins),y=counts,colour=organism))+geom_point()+facet_grid(read_day~trik_ID)+scale_x_continuous(,breaks=seq(1,96,4),labels=seq(1,24,1))+geom_line()


ggplot(c1,aes(x=as.numeric(bins),y=counts,colour=organism))+geom_point()+facet_grid(read_day~trik_ID)+scale_x_continuous(,breaks=seq(1,96,4),labels=seq(1,24,1))+stat_smooth()

## sum counts 
ddply(c1,.(trik_ID,organism,read_day),summarize,counts=sum(counts))
ddply(c1,.(trik_ID,organism),summarize,counts=sum(counts))

```


## creating a sequence of time 

```{r}
t<-hm(c("13:16","16:12"))
time.x = hour(t) + minute(t)/60

d<-seq(time.x[1],time.x[2],length.out=154)

###for whole dataset 

x<-read.csv("../Data/2017-10-03_dataslice.csv")
#x<-read.csv("../Data/test.csv")
x$purge_time_1<-hm(x$purge_time_1)
x$purge1<-hour(x$purge_time_1) + minute(x$purge_time_1)/60

#new.x<-ddply(x,.(cohort_day,tape),transform,seq(from=min(purge1,na.rm=TRUE),to=max(purge1,na.rm=TRUE),length.out=length(purge1)))

new.length<-ddply(x[,-5],.(cohort_day,tape),transform,length=length(Ind_ID))

#new.length<-ddply(x[,-2],.(cohort_day,tape),transform,length=length(purge1))


new.x<-ddply(new.length,.(cohort_day,tape),transform,ftime=seq(from=min(purge1,na.rm=TRUE),to=max(purge1,na.rm=TRUE),length.out=mean(length)))


#new.x<-ddply(new.length,.(cohort_day,tape),summarize,min=min(purge1,na.rm=TRUE),max=max(purge1,na.rm=TRUE))
write.csv(new.x,"test1.csv")

head(new.length)
hms(new.length$resp_time_1)
```


### Session

```{r}
sessionInfo()
```

