---
title: "Calculating Metabolic Rate"
output: html_document
---
### Library

```{r lib}
library(ggplot2)
library(plyr)
library(lubridate)
```

```{r }
t<-hm(c("13:16","16:12"))
time.x = hour(t) + minute(t)/60

d<-seq(time.x[1],time.x[2],length.out=154)

d
###for whole dataset 
x<-read.csv("../Data/2017-08-24_rhagoletis_data_sheet_2017-11-16_dataslice.csv")

#day 10 resp
##purge
x$purge_time_1<-hm(x$purge_time_1)
x$purge1<-hour(x$purge_time_1) + minute(x$purge_time_1)/60
###resp time
x$resp_time1<-hms(x$resp_time_1)
x$resp1<-hour(x$resp_time1) + minute(x$resp_time1)/60

###purge time
# check the number of samples per collection date , cohort day, and tape
ddply(x,.(collection_date,cohort_day,tape),summarize,counts=length(tape))
#new.x<-ddply(x,.(collection_date,cohort_day,tape),transform,ftime=seq(from=min(purge1,na.rm=TRUE),to=max(purge1,na.rm=TRUE),length.out=length(tape)))
#new.x<-ddply(x,.(collection_date,cohort_day,tape),transform,fulltime=24-seq(from=min(purge1,na.rm=TRUE),to=max(purge1,na.rm=TRUE),length.out=length(tape))+resp1)
#new.x<-ddply(x,.(collection_date,cohort_day,tape),transform,MR=resp_day11/(24-seq(from=min(purge1,na.rm=TRUE),to=max(purge1,na.rm=TRUE),length.out=length(tape))+resp1))
head(new.x)


#new.x$Blank<-
blank.dat<-ddply(subset(new.x,Site_name=="Blank"),.(collection_date,cohort_day,tape,Site_name),summarize,Blank.mean=mean(MR,na.rm=TRUE))[,-4]

#library(dplyr)
new.x2<-left_join(new.x,blank.dat,by=c("collection_date","cohort_day","tape"))
dim(new.x2)
new.x2$MR_blank<-(new.x2$MR-new.x2$Blank.mean)/new.x2$mass_day10

new.x3<-ddply(new.x2,.(collection_date,cohort_day,tape),transform,MSMR=MR_blank/(24-seq(from=min(purge1,na.rm=TRUE),to=max(purge1,na.rm=TRUE),length.out=length(tape))+resp1))



new.x4<-subset(new.x3,Site_name!="Blank"& MSMR >0)
#dim(subset(new.x3,MSMR<0))

ggplot(new.x4,aes(y=MSMR,x=Host))+geom_boxplot()

ggplot(new.x4,aes(y=eclosion_days,x=log10(MSMR),colour=Host))+geom_point()+stat_smooth(method="lm",aes(group=1))#+xlim(0,0.0010)

ddply(new.x4,.(Host),summarize,counts=length(MSMR))

mod1<-lm(eclosion_days~log10(MSMR)*Host+cohort_day,data=new.x4)
summary(mod1)
par(mfrow=c(2,2))
plot(mod1)

par(mfrow=c(1,1))

```

### Plots: Histograms and density plots 
```{r}
##histograms of eclosion days 
ggplot(new.x4,aes(x=eclosion_days,fill=Host))+geom_histogram(alpha=.5)

##density plots 
ggplot(new.x4,aes(x=eclosion_days,fill=Host))+geom_density(alpha=.5)


ggplot(new.x3,aes(y=eclosion_days,x=MR,colour=Host))+geom_point()

```


### Session Info
```{r sessioninfo}
sessionInfo()
```

